FROM node:20.17.0-alpine AS builder

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Instala Angular CLI globalmente
RUN npm install -g @angular/cli

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto donde se ejecutará la aplicación Angular
EXPOSE 4200

# Inicia el servidor de desarrollo de Angular con polling para detectar cambios
CMD ["ng", "serve", "--host", "0.0.0.0"]

