# Usa una imagen oficial de Node.js como base
FROM node:20.17.0

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos del proyecto NestJS
COPY package*.json ./
RUN npm install

# Copia el resto del código fuente
COPY . .

# Compila la aplicación NestJS
#RUN npm run build

# Expone el puerto donde se ejecuta la aplicación NestJS
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "run", "start:dev"]
